# Generated by Django 5.0.2 on 2025-04-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=120)),
                ('project', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
    ]
